### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by lscalese** [bdeboe/isc-yaml-utils#1]
Hi @bdeboe ,

Thank you for coding a YAML to JSON converter :-)

I'm starting with a classic OpenAPI yaml file : https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-simple.yaml

If found an issue with list of object : 

```
 parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
```

It seems to be fixed by replacing https://github.com/bdeboe/isc-yaml-utils/blob/7e15796558f976f381b7dde45e3ce3ba2b7bdd19/src/cls/YAML/Utils.cls#L77
 :

```
set key = $Tr($zstrip($e(stripped,1,colon-2),">W"), """", ""), 
``` 
And by adding an elseif https://github.com/bdeboe/isc-yaml-utils/blob/7e15796558f976f381b7dde45e3ce3ba2b7bdd19/src/cls/YAML/Utils.cls#L95 : 

```
} elseif (value="|") {
					set inString = 1
				} elseif isArray {
					Set indent = indent + 1
					set stack(indent) = {}
					do stack(indent).%Set($zstrip($e($p(key,":",1), 2, *),"<W"), value)
					do stack(indent-1).%Push(stack(indent))
					
				}
```
Hope this change won't break anything.

**Comment by bdeboe** [comment]
I think I made the required changes to support both these styles:
```YAML
my-array-style-1:
  - 
    key1: value1
    key2: value2
  - 
    key1: value3
    key2: value4

my-array-style-2:
  - key1: value1
    key2: value2
  - key1: value3
    key2: value4
```
