### ISSUE TITLE
demo for all  3 test cases fail

### ISSUE THREAD

**Issue by r-cemper** [bdeboe/isc-yaml-utils#5]
#1 JSON is truncated * ERROR
```
USER>zw obj
obj={"swagger":"2.0'","info":"\r"}  ; <DYNAMIC OBJECT>

ERROR #5002: ObjectScript error: <UNDEFINED>StreamToJSON+75^YAML.Utils.1 *stack(1)
```
#2 JSON is truncated * ERROR
```
USER>zw obj
obj={"__comment":"# copied as test record from \r\r\n# https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ma
ster/examples/v2.0/yaml/petstore-simple.yaml\r","swagger":"2.0\"","info":"\r"}  ; <DYNAMIC OBJECT>

ERROR #5002: ObjectScript error: <UNDEFINED>StreamToJSON+75^YAML.Utils.1 *stack(1)
```
#3 JSON is truncated * ERROR
```
USER>zw obj
obj={"__comment":"# copied as test record from \r\r\n# https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ma
ster/examples/v2.0/yaml/petstore-simple.yaml\r","swagger":"2.0\"","info":"\r"}  ; <DYNAMIC OBJECT>

ERROR #5002: ObjectScript error: <UNDEFINED>StreamToJSON+75^YAML.Utils.1 *stack(1)
```

**Comment by bdeboe** [comment]
OK, I can see an issue that I'll try to fix when there is an excessive indentation to begin with, but I'm not sure what you mean with the above and how you got to them. Can you attach the source file?

**Comment by r-cemper** [comment]
OK. I met the problem during a Docker test = running IRIS in UBUNTU
searching the example I identified 2 eventually related cases:
#1 - yaml file (with *CRLF* line terminator from Win) cause troubles in UBUNTU
my guess CR is interpreted as additional empty line.
forcing LF as terminator improves hte case
#2 - empty lines ? rather multiple empty lines trigger END of FILE
- files: your iknow.yaml is a good candidate
- I fell over a docker-compose >> next reply

As I lost 3 hrs debugging on a bash script written with CRLF
I did a retry and found a possible reason.

HTH, Robert

**Comment by r-cemper** [comment]
docker compose.yml
--------------------------------------------------------------
version: '3.6'

services:

  iris:
    image: intersystemsdc/iris-community
#   image: intersystemsdc/irishealth-community
    restart: no
    command: /iris-main
      - -a /home/irisowner/dev/ascript.sh
      - -b /home/irisowner/dev/bscript.sh
      - --ISCAgent false

    ports: 
      - 41773:1972
      - 42773:52773
    volumes:
      - ./:/home/irisowner/dev

**Comment by r-cemper** [comment]
with LF only:
USER>zw obj
obj={"version":"3.6","services":{"iris":{"image":"intersystemsdc/iris-community","__comment":"#   image: intersystems
dc/irishealth-community","restart":"no","command":"/iris-main"}}}  ; <DYNAMIC OBJECT>
-----------------------------
USER>w $$Do^ZPretty(o)
{
  "version":"3.6",
  "services":{
    "iris":{
      "image":"intersystemsdc/iris-community",
      "__comment":"#   image: intersystemsdc/irishealth-community",
      "restart":"no",
      "command":"/iris-main"
    }
  }
}
------------------------------------------------------------------------
with WIN terminator CRLF
USER>zw obj
obj={"version":"3.6'","services":"\r"}  ; <DYNAMIC OBJECT>

**Comment by r-cemper** [comment]
[docker-compose.yml.txt](https://github.com/bdeboe/isc-yaml-utils/files/14390986/docker-compose.yml.txt)

**Comment by r-cemper** [comment]
````
version: '3.6'

services:

  iris:
    image: intersystemsdc/iris-community
#   image: intersystemsdc/irishealth-community
    restart: no
    command: /iris-main
      - -a /home/irisowner/dev/ascript.sh
      - -b /home/irisowner/dev/bscript.sh
      - --ISCAgent false
    ports: 
      - 41773:1972
      - 42773:52773
    volumes:
      - ./:/home/irisowner/dev
````
